### ISSUE TITLE
Create-run hangs in applied state

### ISSUE THREAD

**Issue by KamalAman** [hashicorp/tfc-workflows-github#13]
I have a create-run configured and it goes through the steps, but it waits forever (until the timeout) in the applied state

![image](https://github.com/hashicorp/tfc-workflows-github/assets/2692357/d6bf5cde-b1d9-44a7-b16c-aaf2a711cfff)

And eventually: 
<img width="1271" alt="Screen Shot 2023-07-06 at 4 38 11 PM" src="https://github.com/hashicorp/tfc-workflows-github/assets/2692357/ba0be780-4012-49f9-99e3-32e8736dc04d">

This is my configuration 

```
- name: Create Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: create-run
        with:
          organization: "ORG"
          token: ${{ secrets.TERRAFORM_TOKEN }}
          workspace: variables-${{inputs.environment}} 
          message: 'Message (commit: #${{ steps.get-sha.outputs.sha7 }}): ${{ github.event.head_commit.message }}'
```

Why does it sit there forever, and how can I get it go continue after its applied.
