### ISSUE TITLE
TFC Workspace Destroy Feature Request

### ISSUE THREAD

**Issue by fs-david-harrington** [hashicorp/tfc-workflows-github#2979]
Hello Team, 

I would like to propose the ability to queue a destroy plan for a given TFC workspace (not delete it)

... currently Terraform Apply does not support the **--destroy** switch for a TFC workspace. 

or create a new action that supports destroy TFC workspace.

**Comment by snigdhasjg** [comment]
it does. we are using it from past 1 year.

so while creating run you just have to pass `is_destroy` as true

```
    - uses: hashicorp/tfc-workflows-github/actions/create-run@v1.2.0
      id: create-run
      with:
        message: "${{ github.run_number }}-${{ github.run_attempt }}: ${{ github.event.head_commit.message && github.event.head_commit.message || format('Manual trigger by {0} via github', github.triggering_actor) }}"
        workspace: ${{ inputs.workspace }}
        is_destroy: ${{ inputs.is_destroy }}
    - name: Run Destroy
      uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.2.0
      with:
        run: ${{ steps.create-run.outputs.run_id }}
        comment: "Confirmed from GitHub Actions CI by ${{ github.triggering_actor }}"
```
