### ISSUE TITLE
Handle `post_plan_running` status in `apply-run`

### ISSUE THREAD

**Issue by duijf** [hashicorp/tfc-workflows-github#2986]
We have a GitHub action that uses the tooling from this repository that looks very similar to [this example](https://github.com/hashicorp/tfc-workflows-github/blob/main/actions/README.md).

```yaml
      - uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
        id: create-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}

      - uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.2
        # assign id attribute to reference in subsequent steps
        id: apply
        with:
          run: ${{ steps.create-run.outputs.run_id }}
          comment: "Confirmed from GitHub Actions CI"
```

Occasionally, we're observing the following in the `apply-run` step:

```
View Run in HCP Terraform: https://app.terraform.io/app/<redacted>/workspaces/<redacted>/runs/run-<redacted>
run run-<redacted>, cannot be applied
{
  "run_id": "run-<redacted>",
  "run_link": "https://app.terraform.io/app/<redacted>/workspaces/<redacted>/runs/run-<redacted>",
  "run_status": "post_plan_running",
  "status": "Error"
}
```

The workspace in question has Sentinel policies enabled. It looks like either `create-run` returns too early or `apply-run` needs to keep retrying until the `post_plan_running` state / Sentinel policies have passed.
