### ISSUE TITLE
get outputs for use in github actions

### ISSUE THREAD

**Issue by dnsbty** [hashicorp/tfc-workflows-github#7]
Hi! Thank you very much for creating these actions. They've made it a lot easier for me to build out the continuous deployment workflow I want.

One feature request that I have is the ability to get the Terraform outputs to be used in my Github Actions. For instance, after Terraform Apply Run I want to be able to push my Docker image to the AWS ECR repo that I created with Terraform. This requires me to have the repository URL and the AWS IAM role that Github should assume to be able to get the repository login credentials.

For now I've created [a get-terraform-outputs action](https://github.com/marketplace/actions/get-terraform-outputs) to handle this for me, but it would be really nice if this was included in the official workflows.

Or if there's some reason why I shouldn't do this, I would love to know that as well.

Thanks!

**Comment by srlynch1** [comment]
Agree 100% this is required, I also created an issue on this here. 
This is a very common scenario.

https://github.com/hashicorp/tfc-workflows-tooling/issues/9

**Comment by digodk** [comment]
@srlynch1 I see the issue you mentioned is closed. Are you aware if it is possible to get the Terraform outputs with this action now?

**Comment by stuffaboutpete** [comment]
Hi, I appreciate the response. I did see this and tried to use it but it doesn't seem to be 'published' (I don't know how public GitHub actions are authored or shared).

If I update my workflow to include the following job:

```yaml
- name: Get Terraform Outputs
  id: get-terraform-outputs
  uses: hashicorp/tfc-workflows-github/actions/workspace-output@v1.0.0
    with:
      workspace: ${{ env.TF_WORKSPACE }}
```

Firstly, my linter reports:

```
Unable to resolve action `hashicorp/tfc-workflows-github/actions/workspace-output@v1.0.0`, repository or version not found
```

Then when running the action, GitHub Actions reports:

```
Can't find 'action.yml', 'action.yaml' or 'Dockerfile' for action 'hashicorp/tfc-workflows-github/actions/workspace-output@v1.0.0'.
```

The other actions in this repo work just fine. Am I missing something?

## A workaround

For those in my situation who want a quick workaround, copy the contents of the file mentioned in the comment above into your project at `project-root/.github/actions/tfc-workflows-github-workspace-output/action.yml` then update your workflow to refer to the now-local action:

```yaml
- name: Get Terraform Outputs
  id: get-terraform-outputs
  uses: ./.github/actions/tfc-workflows-github-workspace-output
    with:
      workspace: ${{ env.TF_WORKSPACE }}
```

**Comment by phill-lewis** [comment]
@stuffaboutpete Did you try using the latest version v1.3.2? I just set up to use that and it works fine for me.

```
      - name: Workspace Outputs
        uses: hashicorp/tfc-workflows-github/actions/workspace-output@v1.3.2
        id: workspace-output
        with:
          workspace: ${{ env.TF_WORKSPACE }}
```

I also updated all my other relevant actions to the same version.
